##################################################################
# Manual Workflow - to experiment with workflow_dispatch
##################################################################

name: Manually Deploy Main Branch

# Only trigger workflow on updates to main branch
on: 
  workflow_dispatch:
    inputs:
      updateScripts:
        description: 'Should scripts be updated y/n?'
        required: false
        default: 'y'
      updateCreds:
        description: 'Should creds be updated y/n?'
        required: false
        default: 'n'

jobs:
  deploy-creds:
    name: Deploy Creds
    runs-on: self-hosted
    steps:
      - name: Scripts update test
        run: echo "Update scripts = ${{ github.event.inputs.updateScripts }}"
        
      - name: Creds update test
        run: echo "Update creds =  ${{ github.event.inputs.updateCreds }}"
        
      - name: Check out the code
        uses: actions/checkout@v2
        
  deploy-scripts:
    name: Deploy Scripts
    needs: [deploy-creds]
    runs-on: self-hosted
    steps:
      - name: show checkout
        run: ls -lha $GITHUB_WORKSPACE
        
