##################################################################
# Manual Workflow - to experiment with workflow_dispatch
##################################################################

name: Manually Deploy Main Branch

# Only trigger workflow on updates to main branch
on: 
  workflow_dispatch:
    inputs:
      updateScripts:
        description: 'Should scripts be updated y/n?'
        required: false
        default: 'y'
      updateCreds:
        description: 'Should creds be updated y/n?'
        required: false
        default: 'n'

jobs:

  pull-code:
    runs-on: self-hosted
    steps:
      - name: pull github
        uses: actions/checkout@v2
    
  deploy-creds:
    runs-on: self-hosted
    needs: pull-code
    steps:
      - if: github.event.inputs.updateCreds == 'y' 
        name: test creds
        run: |
          echo "Creds update flag is yes"
          cp -rvf $GITHUB_WORKSPACE/creds $HOME/dh/creds
        
  deploy-scripts:
    name: Deploy Scripts
    needs: [pull-code,deploy-creds]
    runs-on: self-hosted
    steps:
      - if: github.event.inputs.updateScripts == 'y' 
        name: test scripts
        run: |
          echo "Scripts update flag is yes"
          cp -rvf $GITHUB_WORKSPACE/scripts $HOME/dh/scripts
        
