name: secrets

on: [push]

jobs:
  s1:
    runs-on: ubuntu-latest
    steps:
    - name: Show secret 1
      run: echo ${{ secrets.TEST_SECRET_1 }}
  
  s2:
    runs-on: windows-latest
    steps:
    - name: Show secret 2
      run: "echo ${{ secrets.TEST_SECRET_2 }}"
      
