name: secrets

on: [push]

env:
  ARTF_SAVE_NAME: mysecrets1.txt
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: save secret 1
      run: echo ${{ secrets.TEST_SECRET_1 }} > ${{ env.ARTF_SAVE_NAME }}
    - name: save secret 2
      run: echo ${{ secrets.TEST_SECRET_2 }} >> ${{ env.ARTF_SAVE_NAME }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        # to upload all files use a "."
        path: ${{ env.ARTF_SAVE_NAME }}
